// Code generated by scripts/generate_types.go; DO NOT EDIT.
// Source: internal/server/protocol, internal/server/viewmodel

export const WS_COMMANDS = ["SyncState", "RequireAction", "NotifyTimeline", "SubmitAction", "RoomAction", "RoomEvent", "ChatMessage", "ProtocolError"] as const
export type WSCommand = typeof WS_COMMANDS[number]

export const ROOM_ACTION_TYPES = ["dissolve_room", "add_bot", "remove_bot", "takeover_player", "change_camp", "change_role", "start"] as const
export type RoomActionType = typeof ROOM_ACTION_TYPES[number]

export const PLAYER_ACTION_TYPES = ["Start", "Quit", "Pass", "Help", "Attack", "Magic", "Buy", "Synthesize", "Extract", "Skill", "CannotAct", "Confirm", "Cancel", "Select", "Respond", "Cheat"] as const
export type PlayerActionType = typeof PLAYER_ACTION_TYPES[number]

export type Element = 'Water' | 'Fire' | 'Earth' | 'Wind' | 'Thunder' | 'Light' | 'Dark'
export type CardType = 'Attack' | 'Magic'
export type Camp = 'Red' | 'Blue'
export type PresentationKind = 'response' | 'branch_select' | 'numeric' | 'card_picker' | 'target_picker' | 'skill_choice' | 'action_hub'
export type CancelPolicy = 'deny' | 'abort' | 'decline' | 'back'

export interface Card {
  id: string
  name: string
  type: CardType
  element: Element
  faction?: string
  damage: number
  description: string
  exclusive_char1?: string
  exclusive_char2?: string
  exclusive_skill1?: string
  exclusive_skill2?: string
}

export interface Buff {
  id: string
  name: string
  duration: number
  value: number
  source_id: string
}

export interface FieldCard {
  card: Card
  owner_id: string
  source_id: string
  mode: 'Effect' | 'Cover'
  effect: string
  field_hook: string
  locked: boolean
  duration: number
}

export interface PromptPresentation {
  kind: PresentationKind
  layout?: string
  numeric_base: number
  cancel_policy?: CancelPolicy
  cancel_label?: string
  target_filter?: 'all' | 'enemies' | 'allies' | 'allies_exclude_self' | 'any_exclude_self' | 'custom'
  multi_target?: boolean
  card_source?: 'hand' | 'field' | 'proxy'
  card_filter?: string
  discard_reason?: string
  has_decline?: boolean
  decline_index?: number
  step_index?: number
  total_steps?: number
}

export interface ActionStepPayload {
  line: string
  kind: string
}

export interface AvailableSkill {
  id: string
  title: string
  description: string
  min_targets: number
  max_targets: number
  target_type: number
  cost_gem: number
  cost_crystal: number
  cost_discards: number
  discard_type?: string
  discard_element?: string
  require_exclusive?: boolean
  place_card?: boolean
  place_effect?: string
}

export interface CardRevealedPayload {
  player_id: string
  player_name: string
  cards: Card[]
  action_type: string
  hidden: boolean
}

export interface CharacterView {
  id: string
  name: string
  title: string
  faction: string
  skills: SkillView[]
}

export interface ClientActionRequest {
  action_type: PlayerActionType
  card_id?: string
  card_ids?: string[]
  targets?: TargetNode[]
  skill_id?: string
  option_indexes?: number[]
  extra_args?: string[]
}

export interface CombatCuePayload {
  attacker_id: string
  target_id: string
  phase: string
}

export interface DamageDealtPayload {
  source_id: string
  source_name: string
  target_id: string
  target_name: string
  damage: number
  damage_type: string
}

export interface DrawCardsPayload {
  player_id: string
  player_name: string
  draw_count: number
  reason: string
}

export interface GameStateUpdate {
  turn_stage?: string
  combat_stage?: string
  subflow?: string
  current_player: string
  has_performed_startup: boolean
  players: Record<string, PlayerView>
  red_morale: number
  blue_morale: number
  red_cups: number
  blue_cups: number
  red_gems: number
  blue_gems: number
  red_crystals: number
  blue_crystals: number
  deck_count: number
  discard_count: number
  available_skills: AvailableSkill[]
  characters?: CharacterView[]
}

export interface PlayerInfo {
  id: string
  name: string
  camp: string
  char_role: string
  ready: boolean
  is_online: boolean
  is_bot?: boolean
  is_host?: boolean
  bot_mode?: string
}

export interface PlayerView {
  id: string
  name: string
  camp: string
  role: string
  orientation?: string
  form?: string
  hand_count: number
  max_hand: number
  exclusive_card_count: number
  hand?: Card[]
  exclusive_cards?: Card[]
  field: FieldCard[]
  heal: number
  max_heal: number
  gem: number
  crystal: number
  is_active: boolean
  buffs: Buff[]
  tokens?: Record<string, number>
  indicators?: Record<string, number>
  current_extra_action?: string
  current_extra_element?: string[]
}

export interface PromptDTO {
  type: string
  player_id: string
  message: string
  choice_type?: string
  skill_id?: string
  options: PromptOptionDTO[]
  special_options?: PromptOptionDTO[]
  ui_mode?: string
  presentation: PromptPresentation
  interaction?: PromptInteractionDTO
  effect_hints?: string[]
  min: number
  max: number
  attacker_id?: string
  counter_target_ids?: string[]
  attack_element?: string
}

export interface PromptInteractionDTO {
  selection_source: string
  selection_value: string
  confirm_mode: string
  submit_action: string
}

export interface PromptOptionDTO {
  id: string
  label: string
  button_label: string
  hint?: string
  card_id?: string
  target_id?: string
  field_index?: number
  element?: string
}

export interface ProtocolErrorPayload {
  code: string
  message: string
  cmd?: WSCommand
  context?: Record<string, unknown>
}

export interface RequireActionPayload {
  interrupt_type: string
  target_user_id: string
  timeout: number
  msg: string
  valid_actions?: WSCommand[]
  require_count?: number
  prompt_type?: string
  prompt?: PromptDTO
}

export interface RoomActionRequest {
  action: RoomActionType
  camp?: string
  char_role?: string
  target_id?: string
  bot_name?: string
}

export interface RoomEvent {
  action: string
  room_code: string
  player_id?: string
  player_name?: string
  players?: PlayerInfo[]
  characters?: CharacterView[]
  message?: string
  camp?: string
  char_role?: string
  reconnect_token?: string
}

export interface SkillView {
  id: string
  title: string
  description: string
  type: number
  min_targets: number
  max_targets: number
  target_type: number
  cost_gem: number
  cost_crystal: number
  cost_discards: number
  discard_element?: string
  require_exclusive?: boolean
}

export interface SyncStatePayload {
  room_state: string
  turn_stage?: string
  combat_stage?: string
  subflow?: string
  turn_player_id: string
  has_performed_startup: boolean
  morale_red: number
  morale_blue: number
  cups_red: number
  cups_blue: number
  stones_red: number[]
  stones_blue: number[]
  deck_count: number
  discard_count: number
  available_skills?: AvailableSkill[]
  characters?: CharacterView[]
  players: PlayerView[]
}

export interface TargetNode {
  target_user_id?: string
  selected_field_cards?: string[]
  selected_hand_cards?: string[]
  selected_tokens?: string[]
}

export interface TimelineDelta {
  type: string
  target_user_id?: string
  value?: number
}

export interface TimelineEvent {
  event_id: number
  turn_id: number
  turn_stage?: string
  combat_stage?: string
  subflow?: string
  timing?: string
  chain_id: string
  parent_event_id?: number
  type: string
  outcome: string
  visibility: string
  actor_user_id?: string
  actor_name?: string
  target_user_ids?: string[]
  target_name?: string
  action_type?: string
  skill_id?: string
  card_ids?: string[]
  cards?: Card[]
  hidden?: boolean
  damage?: number
  damage_type?: string
  detail_kind?: string
  cue_phase?: string
  draw_count?: number
  reason?: string
  deltas?: TimelineDelta[]
  message?: string
  gameplay_type?: string
}

export interface TimelineNotifyPayload {
  room_id: string
  seq_start: number
  seq_end: number
  is_replay: boolean
  events: TimelineEvent[]
}

export interface WSMessage {
  Cmd: WSCommand
  Data?: unknown
}

export type GameplayEvent =
  | { event_type: 'log'; message: string }
  | { event_type: 'state_update'; state: GameStateUpdate }
  | { event_type: 'prompt'; prompt: PromptDTO }
  | { event_type: 'waiting'; player_id: string }
  | { event_type: 'error'; message: string }
  | { event_type: 'game_end'; message: string }
  | { event_type: 'chat'; player_id: string; player_name: string; message: string }
  | ({ event_type: 'card_revealed' } & CardRevealedPayload)
  | ({ event_type: 'damage_dealt'; message?: string } & DamageDealtPayload)
  | ({ event_type: 'action_step'; line: ActionStepPayload['line']; kind: ActionStepPayload['kind'] })
  | ({ event_type: 'combat_cue'; attacker_id: CombatCuePayload['attacker_id']; target_id: CombatCuePayload['target_id']; phase: CombatCuePayload['phase'] })
  | ({ event_type: 'draw_cards'; player_id: DrawCardsPayload['player_id']; player_name: DrawCardsPayload['player_name']; draw_count: DrawCardsPayload['draw_count']; reason: DrawCardsPayload['reason'] })
