package model

const (
	TimingGameInitial        Timing = "game.initial"
	TimingFieldMarkChanged   Timing = "system.field_mark_changed"
	TimingOrientationChanged Timing = "system.orientation_changed"
	TimingTurnBeforeStart    Timing = "turn.before_start"
	TimingTurnStart          Timing = "turn.start"
	TimingActionBefore       Timing = "turn.action_before"
	TimingActionStart        Timing = "turn.action_start"
	TimingActionDuring       Timing = "turn.action_during"
	TimingActionEnd          Timing = "turn.action_end"
	TimingActionPost         Timing = "turn.action_post"
	TimingTurnEnd            Timing = "turn.end"

	TimingAttackDeclare         Timing = "attack.declare"
	TimingAttackSelectTarget    Timing = "attack.select_target"
	TimingAttackPlayCard        Timing = "attack.play_card"
	TimingAttackModifyCard      Timing = "attack.modify_card"
	TimingAttackCommitted       Timing = "attack.committed"
	TimingAttackForceHitCheck   Timing = "attack.force_hit_check"
	TimingAttackNoResponseCheck Timing = "attack.no_response_check"
	TimingAttackResponse        Timing = "attack.response"
	TimingAttackHit             Timing = "attack.hit"
	TimingAttackMiss            Timing = "attack.miss"

	TimingMagicDeclare      Timing = "magic.declare"
	TimingMagicSelectTarget Timing = "magic.select_target"
	TimingMagicValidate     Timing = "magic.validate"
	TimingMagicResolve      Timing = "magic.resolve"
	TimingMagicHealOverflow Timing = "magic.heal_overflow"

	TimingMagicMissileResponse      Timing = "magic.missile.response"
	TimingMagicMissileDefend        Timing = "magic.missile.defend"
	TimingMagicMissileCounter       Timing = "magic.missile.counter"
	TimingMagicMissileResponseSkill Timing = "magic.missile.response_skill"

	TimingDamageSourceDeal   Timing = "damage.source_deal"
	TimingDamageTargetBefore Timing = "damage.target_before"
	TimingHealBefore         Timing = "heal.before"
	TimingHealUse            Timing = "heal.use"
	TimingHealCap            Timing = "heal.cap"
	TimingDamageApplied      Timing = "damage.applied"
	TimingDamageTaken        Timing = "damage.taken"
	TimingSettleDraw         Timing = "settle.draw"
	TimingSettleDiscard      Timing = "settle.discard"
	TimingCardPlayedRevealed Timing = "settle.card_played_revealed"
	TimingSettleHandLimit    Timing = "settle.hand_limit_check"
	TimingMoraleLossCheck    Timing = "settle.morale_loss_check"
	TimingMoraleLossApplied  Timing = "settle.morale_loss_applied"
	TimingGameEndCheck       Timing = "settle.game_end_check"
	TimingDamageResolved     Timing = "damage.resolved"
)
