package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type fieldDef struct {
	Name     string
	JSONName string
	Optional bool
	Type     string
}

type typeDef struct {
	Name   string
	Fields []fieldDef
}

var emitted = map[string]bool{}
var structs = map[string]typeDef{}
var enumValues = map[string][]string{}

type enumSource struct {
	Path  string
	Types map[string]bool
}

var includeTypes = map[string]bool{
	"AvailableSkill":        true,
	"CharacterView":         true,
	"ClientActionRequest":   true,
	"GameStateUpdate":       true,
	"CardRevealedPayload":   true,
	"DamageDealtPayload":    true,
	"ActionStepPayload":     true,
	"ActionFlowActorDTO":    true,
	"ActionFlowDTO":         true,
	"ActionFlowEdgeDTO":     true,
	"ActionFlowLogDTO":      true,
	"ActionFlowNodeDTO":     true,
	"CombatCuePayload":      true,
	"DrawCardsPayload":      true,
	"PlayerInfo":            true,
	"PlayerView":            true,
	"PromptDTO":             true,
	"PromptInteractionDTO":  true,
	"PromptOptionDTO":       true,
	"ProtocolErrorPayload":  true,
	"RequireActionPayload":  true,
	"RoomActionRequest":     true,
	"RoomEvent":             true,
	"SyncStatePayload":      true,
	"SkillView":             true,
	"TargetNode":            true,
	"TimelineDelta":         true,
	"TimelineEvent":         true,
	"TimelineNotifyPayload": true,
	"WSMessage":             true,
}

var includeEnums = map[string]string{
	"WSCommand":        "WS_COMMANDS",
	"RoomActionType":   "ROOM_ACTION_TYPES",
	"PlayerActionType": "PLAYER_ACTION_TYPES",
}

var builtinAliases = map[string]string{
	"json.RawMessage":          "unknown",
	"model.Buff":               "Buff",
	"model.Card":               "Card",
	"model.FieldCard":          "FieldCard",
	"model.PlayerActionType":   "PlayerActionType",
	"model.PromptPresentation": "PromptPresentation",
	"viewmodel.AvailableSkill": "AvailableSkill",
	"viewmodel.CharacterView":  "CharacterView",
	"viewmodel.PlayerView":     "PlayerView",
	"viewmodel.PromptDTO":      "PromptDTO",
	"protocol.RoomActionType":  "RoomActionType",
	"protocol.WSCommand":       "WSCommand",
	"map[string]interface{}":   "Record<string, unknown>",
	"interface{}":              "unknown",
	"string":                   "string",
	"int":                      "number",
	"int64":                    "number",
	"bool":                     "boolean",
}

func main() {
	root, err := os.Getwd()
	if err != nil {
		fatal(err)
	}
	for _, dir := range []string{
		filepath.Join(root, "internal/model"),
		filepath.Join(root, "internal/server/protocol"),
		filepath.Join(root, "internal/server/viewmodel"),
	} {
		if err := collectStructs(dir); err != nil {
			fatal(err)
		}
	}
	for _, source := range []enumSource{
		{
			Path: filepath.Join(root, "internal/model/protocol.go"),
			Types: map[string]bool{
				"PlayerActionType": true,
			},
		},
		{
			Path: filepath.Join(root, "internal/server/protocol/types.go"),
			Types: map[string]bool{
				"WSCommand":      true,
				"RoomActionType": true,
			},
		},
	} {
		if err := collectEnumValues(source.Path, source.Types); err != nil {
			fatal(err)
		}
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by scripts/generate_types.go; DO NOT EDIT.\n")
	out.WriteString("// Source: internal/server/protocol, internal/server/viewmodel\n\n")
	for _, enumName := range []string{"WSCommand", "RoomActionType", "PlayerActionType"} {
		emitEnum(&out, enumName)
	}
	out.WriteString("export type Element = 'Water' | 'Fire' | 'Earth' | 'Wind' | 'Thunder' | 'Light' | 'Dark'\n")
	out.WriteString("export type CardType = 'Attack' | 'Magic'\n")
	out.WriteString("export type Camp = 'Red' | 'Blue'\n")
	out.WriteString("export type PresentationKind = 'response' | 'branch_select' | 'numeric' | 'card_picker' | 'target_picker' | 'skill_choice' | 'action_hub'\n")
	out.WriteString("export type CancelPolicy = 'deny' | 'abort' | 'decline' | 'back'\n\n")
	out.WriteString("export interface Card {\n")
	out.WriteString("  id: string\n  name: string\n  type: CardType\n  element: Element\n  faction?: string\n  damage: number\n  description: string\n  exclusive_char1?: string\n  exclusive_char2?: string\n  exclusive_skill1?: string\n  exclusive_skill2?: string\n}\n\n")
	out.WriteString("export interface Buff {\n")
	out.WriteString("  id: string\n  name: string\n  duration: number\n  value: number\n  source_id: string\n}\n\n")
	out.WriteString("export interface FieldCard {\n")
	out.WriteString("  card: Card\n  owner_id: string\n  source_id: string\n  mode: 'Effect' | 'Cover'\n  effect: string\n  field_hook: string\n  locked: boolean\n  duration: number\n}\n\n")
	out.WriteString("export interface PromptPresentation {\n")
	out.WriteString("  kind: PresentationKind\n  layout?: string\n  numeric_base: number\n  cancel_policy?: CancelPolicy\n  cancel_label?: string\n  target_filter?: 'all' | 'enemies' | 'allies' | 'allies_exclude_self' | 'any_exclude_self' | 'custom'\n  multi_target?: boolean\n  card_source?: 'hand' | 'field' | 'proxy'\n  card_filter?: string\n  discard_reason?: string\n  has_decline?: boolean\n  decline_index?: number\n  step_index?: number\n  total_steps?: number\n}\n\n")

	names := make([]string, 0, len(includeTypes))
	for name := range includeTypes {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		emitType(&out, name)
	}
	emitGameplayEventUnion(&out)

	target := filepath.Join(root, "web/src/types/generated.ts")
	generated := append(bytes.TrimRight(out.Bytes(), "\n"), '\n')
	if err := os.WriteFile(target, generated, 0644); err != nil {
		fatal(err)
	}
}

func collectStructs(dir string) error {
	return filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		file, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.ParseComments)
		if err != nil {
			return err
		}
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				structs[ts.Name.Name] = typeDef{Name: ts.Name.Name, Fields: collectFields(st)}
			}
		}
		return nil
	})
}

func collectEnumValues(path string, allowedTypes map[string]bool) error {
	file, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.ParseComments)
	if err != nil {
		return err
	}

	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.CONST {
			continue
		}

		currentType := ""
		for _, spec := range gen.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			if vs.Type != nil {
				currentType = typeName(vs.Type)
			}
			if !allowedTypes[currentType] {
				continue
			}

			for i := range vs.Names {
				if i >= len(vs.Values) {
					continue
				}
				lit, ok := vs.Values[i].(*ast.BasicLit)
				if !ok || lit.Kind != token.STRING {
					continue
				}
				value, err := strconv.Unquote(lit.Value)
				if err != nil {
					return err
				}
				enumValues[currentType] = append(enumValues[currentType], value)
			}
		}
	}

	return nil
}

func collectFields(st *ast.StructType) []fieldDef {
	var fields []fieldDef
	for _, f := range st.Fields.List {
		if len(f.Names) == 0 {
			continue
		}
		jsonName, optional, skip := jsonTag(f.Tag)
		if skip {
			continue
		}
		for _, name := range f.Names {
			fieldName := jsonName
			if fieldName == "" {
				fieldName = lowerCamel(name.Name)
			}
			fields = append(fields, fieldDef{
				Name:     name.Name,
				JSONName: fieldName,
				Optional: optional,
				Type:     tsType(f.Type),
			})
		}
	}
	return fields
}

func jsonTag(tag *ast.BasicLit) (name string, optional bool, skip bool) {
	if tag == nil {
		return "", false, false
	}
	raw := strings.Trim(tag.Value, "`")
	for _, part := range strings.Split(raw, " ") {
		if !strings.HasPrefix(part, "json:") {
			continue
		}
		value := strings.Trim(strings.TrimPrefix(part, "json:"), "\"")
		pieces := strings.Split(value, ",")
		if len(pieces) == 0 || pieces[0] == "-" {
			return "", false, true
		}
		for _, piece := range pieces[1:] {
			if piece == "omitempty" {
				optional = true
			}
		}
		return pieces[0], optional, false
	}
	return "", false, false
}

func tsType(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		if alias, ok := builtinAliases[t.Name]; ok {
			return alias
		}
		return t.Name
	case *ast.SelectorExpr:
		key := selectorName(t)
		if alias, ok := builtinAliases[key]; ok {
			return alias
		}
		return t.Sel.Name
	case *ast.StarExpr:
		return tsType(t.X)
	case *ast.ArrayType:
		return tsType(t.Elt) + "[]"
	case *ast.MapType:
		key := tsType(t.Key)
		if key != "string" {
			key = "string"
		}
		return fmt.Sprintf("Record<%s, %s>", key, tsType(t.Value))
	case *ast.InterfaceType:
		return "unknown"
	default:
		return "unknown"
	}
}

func emitType(out *bytes.Buffer, name string) {
	if emitted[name] {
		return
	}
	def, ok := structs[name]
	if !ok {
		return
	}
	emitted[name] = true
	out.WriteString("export interface " + name + " {\n")
	for _, f := range def.Fields {
		opt := ""
		if f.Optional {
			opt = "?"
		}
		out.WriteString(fmt.Sprintf("  %s%s: %s\n", f.JSONName, opt, f.Type))
	}
	out.WriteString("}\n\n")
}

func emitEnum(out *bytes.Buffer, typeName string) {
	constName, ok := includeEnums[typeName]
	if !ok {
		return
	}
	values := uniqueStrings(enumValues[typeName])
	if len(values) == 0 {
		return
	}

	out.WriteString("export const " + constName + " = [")
	for i, value := range values {
		if i > 0 {
			out.WriteString(", ")
		}
		out.WriteString(strconv.Quote(value))
	}
	out.WriteString("] as const\n")
	out.WriteString("export type " + typeName + " = typeof " + constName + "[number]\n\n")
}

func uniqueStrings(values []string) []string {
	seen := map[string]struct{}{}
	out := make([]string, 0, len(values))
	for _, value := range values {
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		out = append(out, value)
	}
	return out
}

func emitGameplayEventUnion(out *bytes.Buffer) {
	out.WriteString("export type GameplayEvent =\n")
	out.WriteString("  | { event_type: 'log'; message: string }\n")
	out.WriteString("  | { event_type: 'state_update'; state: GameStateUpdate }\n")
	out.WriteString("  | { event_type: 'prompt'; prompt: PromptDTO }\n")
	out.WriteString("  | { event_type: 'waiting'; player_id: string }\n")
	out.WriteString("  | { event_type: 'error'; message: string }\n")
	out.WriteString("  | { event_type: 'game_end'; message: string }\n")
	out.WriteString("  | { event_type: 'chat'; player_id: string; player_name: string; message: string }\n")
	out.WriteString("  | ({ event_type: 'card_revealed' } & CardRevealedPayload)\n")
	out.WriteString("  | ({ event_type: 'damage_dealt'; message?: string } & DamageDealtPayload)\n")
	out.WriteString("  | ({ event_type: 'action_step'; line: ActionStepPayload['line']; kind: ActionStepPayload['kind'] })\n")
	out.WriteString("  | ({ event_type: 'combat_cue'; attacker_id: CombatCuePayload['attacker_id']; target_id: CombatCuePayload['target_id']; phase: CombatCuePayload['phase'] })\n")
	out.WriteString("  | ({ event_type: 'draw_cards'; player_id: DrawCardsPayload['player_id']; player_name: DrawCardsPayload['player_name']; draw_count: DrawCardsPayload['draw_count']; reason: DrawCardsPayload['reason'] })\n\n")
	out.WriteString("  | { event_type: 'skill_activated'; player_id: string; player_name: string; skill_id: string; skill_name: string; effect_text: string; target_ids?: string[] }\n")
	out.WriteString("  | { event_type: 'special_action'; player_id: string; player_name: string; action_type: string; target_ids?: string[]; summary: string }\n")
	out.WriteString("  | { event_type: 'state_delta'; deltas: TimelineDelta[]; reason?: string }\n\n")
}

func selectorName(sel *ast.SelectorExpr) string {
	if x, ok := sel.X.(*ast.Ident); ok {
		return x.Name + "." + sel.Sel.Name
	}
	return sel.Sel.Name
}

func typeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return selectorName(t)
	default:
		return ""
	}
}

func lowerCamel(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
